### ISSUE TITLE
Several questions about... (the scoring system for quizzes/navigation/...)

### ISSUE THREAD

**Issue by rfuehrer** [LiaScript/LiaScript#117]
I have several basic questions about LiaScript, as I support the open codes system for knowledge and would like to promote it in our company.

We use an LMS (CornerStone) to which content will be contributed by various development projects. The projects are familiar with Markdown, so LiaScript is a great fit.

However, for training materials, it is necessary for the learning process and a possible assessment of the learning progress that some functions can be mapped in the SCORM for CornerStone. Can you give a hint if the following functions are possible or already implemented:

1. For solving a task, no possibility of solution should be displayed on the first attempt, so that the user has to make at least one attempt. 

2. the number of solution attempts should be limited and the solution should be solved automatically after the second attempt (or even a later attempt).

3. The correct solution should reward the question with a point. Automatic solving does not. In the end, the total number of points should decide the result. How can this score be queried? The SCORM exporter can specify the maximum number of points, to which internal state does this specification refer?

4. Can a reset of the points be achieved by the user, so that e.g. incorrect questions are answered again and thus the maximum achievable score is reset?

5. Can the score be displayed as a variable within the course?

6. Is it possible to jump between chapters, so that a non-linear course is created or is the navigation always linear?

8. Can the display/call of a page/chapter be linked to the number of points or other preconditions, so that e.g. a completion is only possible after reaching the minimum number of points?

9. Related to a SCORM export: which condition would lead to the state "successfully participated" (completed)?

KR

**Comment by andre-dietrich** [comment]
Hi @rfuehrer ... these are a couple of questions, I hope that I understand them fully:

1. This would be a nice addon, as we did this for randomizing quizzes (https://github.com/LiaScript/LiaScript/issues/112), such options could be added as a quiz configuration 
   ``` markdown
   <!-- data-randomize data-max-trials="5" data-show-solution-button="0"-->
   - [(X)] option 1
   - [( )] option 2
   - [( )] option 3
   ```
   
   At the moment this would also be possible, but with some hacky javascript, that not that nice ... However, we could think of such options, similarly as we did this for tables and data-visualization: [doc-tables](https://liascript.github.io/course/?https://raw.githubusercontent.com/liaScript/docs/master/README.md#152)
   
   **However, if you have knowledge of nice standards and naming-conventions, that we can utilize, I would be happy to add such features ...** We could discuss the details in a separate issue ;-)
   
2. As above, this could be added as a parameter `data-max-trials="3"`
3. The SCORM export ranges all quizzes and surveys equally. It is possible to define the percentage correctly solved quizzes and submitted surveys. Their current state is stored within SCROM as a JSON, such that the Teacher can review the results. And the happily solved course is then determined by the number of correctly solved quizzes. Resolve is not counted as correct, but of course, you have endless trials within the correct configuration.
4. A reset should not be possible, since the state is stored within the SCORM-backend, this is only possible on the website, where all courses are only for personal use ...
5. I don't know if this is implemented, but this should be possible. A global variable that is displayed within a script-tag ...
6. Jumping is possible, either by linking as in Markdown or automatically by a script-tag, every LiaScript has a global `LIA` object, that can be used for navigation:

   ``` markdown
   what is 2*33?

    [[66]]
    <script>
    if ("@input" == "66") {
      setTimeout(()=>{
        // Jump to the second slide after 5 seconds 
        LIA.goto(2)
      }, 5000)
      true
    } else {
      false
    }
    </script>
   ```

   In the same way also a counter for a maximum number of trials could be implemented, but I like the idea of adding options to the header-comment.

7. No, I think this is not possible by default. At the beginning of the project, we had also a linear progress in mind, such that you cannot jump to another page, if the previous was not visited, but we had rejected this idea to enable a quick and fast access to the entire content. I remember a solution of a course-creator, who had hidden the entire table of contents row and only showed the next section, if the previous was visited, but that required a hacky solution with javascript, and he had to store the progress also manually within the browser...

8. As mentioned earlier, if there are 10 quizzes, then all valued equally (this would also be an interesting idea, to add points or a ranking to the comment attached). When creating a course with the exporter and adding the option `--scorm-masteryScore 90` then 90% of the quizzes have to be solved correctly.

I hope this answers your questions...

**Comment by andre-dietrich** [comment]
I mean, it would be good if we could relay on some naming-conventions, like they are probably used in CornerStone or other LMS.

* One option might be named `data-max-trials`, simple and clear
* but, I don't know how to name the option properly, if the "resolve" button should be visible after a certain amount of steps, `data-show-resolve-button-at="2"`, where the number indicated the amount of trials, might be a bit to long ...
* `data-rank/level/point="3"` might indicate a level of difficulty, how is this solved in Articulate?
* ... maybe there are also other options that we could take into account ? 

German is also okay ;-)

**Comment by rfuehrer** [comment]
Hallo André,

ich Wechsel mal auf Deutsch, obwohl der Austausch dann für die Community ggf. verloren geht :)

Meine 2 cents:

`data-max-trials` finde ich von der Begrifflichkeit erst einmal passend, müsste aber einen Default von 1 haben, damit die Bezeichnung es Sinn macht. Eine Nutzerangabe von 0 würde auf den Default fallen, könnte aber zu Missverständnissen führen. Allerdings wäre `data-max-fails' nicht unbedingt eindeutiger, da auch hier  IMHO eine Angabe von 0 und 1 gleichbedeutender sind. Natürlich geht bei beiden Angaben auch die Annahme, dass 0 ein ungültiger Wert ist und programmatisch auf 1 gesetzt wird.

`data-show-solution-button` würde ich fast sogar in (so oder ähnlich) `data-enable-resolve-from-trial` verstehen, dann hätte 0 die Auswirkung den Button umgehend zu zeigen und jede Angabe größer 0 die entsprechende Anzahl vorheriger Versuche. Allerdings ist mir der Bezeichnet fast schon zu lang - aber dafür eben auch sprechend.

Ich habe mir einen Demo-Account in der Articulate Cloud angelegt und dort in einem Demo-Kurs  festgestellt, dass jedes Quiz nur einen Lösungsversuch hat. Das passt in dem Fall sogar recht gut. Bei Falschauswahl wird ein Hinweistext zur fehlerhaften Auswahl angezeigt. Es sind 5 Quizzes in dem einen Format an einer zentralen Stelle gewesen und wenn man am Ende der 5 Fragen nicht 80% richtige Beantwortung erreicht hat, kann man das Quiz zurücksetzen (`score`= 0 und Quiz mit allen Fragen re-intitialisiert). Das würde bei dem liascript-Aufbau vermutlich dazu führen, dass man zwischen Quizzes gesamtheitlich und in jeweiligen Scopes unterscheiden möchte. Allerdings wäre in meiner Wahrnehmung für einen MVP der gesamtheitliche Ansatz interessant/relevant. Abe mit Blick auf Erweiterung ist der Scope-Ansatz durchaus auch interessant. Theoretisch könnte dann der kumulierte prozentuale Erfüllungsgrad der Scope-Quizzes dann am Ende zu dem Gesamt-Score führen... Aber das ist eine deutlich höhere Komplexität und geht über das hinaus was liascript aus macht.

**Comment by andre-dietrich** [comment]
Ich habe erstmal testweise die drei Konfigurationsmöglichkeiten `data-max-trials`, `data-score`, `data-show-solution-button` eingefügt... bei dem Lösungsknopf versuche ich noch die Optionen `="true|false|on|off|0...n"` einzufügen ... ich würde es so verstehen, man kann es generell aus- und einschalten, wobei die Zahlen dann für den Versuch stehen, ab dem Wievielten dieser angezeigt wird ... würde es nächste Woche mal mit dem SCORM-Export testen, dort muss auch noch der `score`-Wert interpretiert werden ...

**Comment by rfuehrer** [comment]
Das klingt sehr cool. Wie würdest Du die Ziffer Null "0" bei der numerischen Angabe interpretieren? 

1 => an, mit Anzeige nach ersten Versuch
2 => an, mit Anzeige nach zweiten Versuch
3 => ...

Bedeute "0" dann "Anzeige bereits vor dem ersten Versuch" oder "aus"? Konsistent wäre "Anzeige nach 0. Versuch aka vor erstem Versuch".

Wenn ich etwas testen kann/darf, sag bitte gerne Bescheid. 

Ich habe kommende Woche mit unserem Team, das Inhalte nach CornerStone bereitstellt. Ich möchte bei dem Termin ergründen, ob der Import eines liascript Exports sich integrieren lässt und ob es einen funktionalen Mehrwert bietet. Derzeit haben wir entweder nur komplexe Inhalte Dritter oder "video-fizierte Inhalte" ohne Quiz. liascript wäre eine schöne Gelegenheit die Lücke zwischen den (bei uns bestehenden) "Extremen" für agile Team mit mehr Self-Service zu füllen.

**Comment by rfuehrer** [comment]
Danke Dir für die Implementierung, wie kann ich denn die neuen Parameter am besten testen?

**Comment by andre-dietrich** [comment]
Jetzt müsste es online sein ... einfach den Editor oder DevServer updaten und auch den Exporter ... Ich habe es mit Ilias getestet, dort funktionieren die Änderungen jetzt ... Die Zustände der Quizze und Umfragen werden gespeichert, wenn der Nutzer sich im Zustand Normal befindet. In Moodle gibt es auch einen Normal und Preview-Mode ... Die Doku müsste nur noch angepasst werden ...

**Comment by andre-dietrich** [comment]
PS: Im Browser einfach Ctrl-F5 drücken ;-) ... manchmal brauchen die Service-Worker einen kleinen Anstoß ...

**Comment by rfuehrer** [comment]
ahhh, gefunden. der oben dargestellte Parameter hatte noch "show" im Namen :D Habe es wie im Changelog beschrieben korrigiert und es geht. Klasse! Danke Dir.

**Comment by rfuehrer** [comment]
...sorry für das nerven :) Wir hatten den `Score` ein bisschen aus den Augen verloren ;) Ist denn innerhalb eines Liascript der aktuelle Stand der Beantwortung erkennbar? Ich würde am Ende gerne einen Gauge (vergl. Articulate) darstellen, der den Erreichten %-Score darstellt und den zum Abschluss erforderlichen - ist so etwas möglich?

![256](https://user-images.githubusercontent.com/25303664/220333081-5ba52201-ffcc-416a-970c-65b1e36c38c3.png)

Oder lieber eigenes Issue?

**Comment by andre-dietrich** [comment]
In LiaScript kann man echarts nutzen, dafür gibt es eine eingebaute WebComponente. Man könnte sowas wie das folgende nutzen ... 

``` markdown
<script style="display: block" modify="false">
  const gauge = {
  tooltip: {
    formatter: '{a} <br/>{b} : {c}%'
  },
  series: [
    {
      name: 'Progress',
      type: 'gauge',
      progress: {
        show: true
      },
      detail: {
        valueAnimation: true,
        formatter: '{value}'
      },
      data: [
        {
          value: window.SCORE || 0,
          name: 'SCORE'
        }
      ]
    }
  ]
};

`HTML: <lia-chart option='${JSON.stringify(gauge)}'></lia-chart>`
</script>
```

Ich habe nur das Beispiel von echarts für gauge genommen:

https://echarts.apache.org/examples/en/editor.html?c=gauge-simple
https://echarts.apache.org/examples/en/index.html#chart-type-gauge

es noch weitere Möglichkeiten bei dieser Darstellung den Stil zu ändern ...

Innerhalb des Exports nach Scorm 2004 wird derzeitig der Fortschritt unter der globalen Variable `window.SCORE` gespeichert, als Wert zwischen 0 und 1.

Der letzte String ist die zu interpretierende Ausgabe, das Resultat des Scripts, das direkt ausgegeben wird ... HTML: sagt, interpretier es ... als HTML, sonst wird nur der Text angezeigt ... das script kann auch stylen, die möglichen Optionen sind in der Doku (diesmal vollständig) ;-) ...

**Comment by andre-dietrich** [comment]
Ok, hatte mich in der SCORM-Cloud testweise angemeldet ... damit der Score in der Übersicht angezeigt wird, musste ich noch einen extra-scorm-Wert setzen "cmi.score.scaled".

![SCORM](https://user-images.githubusercontent.com/3089101/220412758-fa59056c-486c-45ec-b34a-25961c5de459.png)

Damit das LiaScript-Paket auch den SCORM-Endpunkt findet, musste ich bei Combatibilty-Settings Wream SCO Window with API setzen.

![SCORM-Compaible](https://user-images.githubusercontent.com/3089101/220413076-68445cd2-54a2-4f0a-b33f-76554426aae0.png)

... some poorly implemented SCORM content ... finde ich schon ziemlich frech, SCORM ist so ziemlich der schwerste Standard, den ich je versucht habe zu verstehen ... 

Hoffe das hilft ... Merke, nochmal den LiaScript-Exporter updaten, nur den ...

**Comment by rfuehrer** [comment]
Vorab: Danke Dir im übrigen für die schnelle und umfangreiche Hilfe. Wenn ich etwas beisteuern kann, dann sag bitte gerne Bescheid. Am Montag habe ich mit unserem LMS-Team den Termin, in dem ich LiaScript bzw. den Import von User-Created-Content bespreche. Wenn das angenommen wird, möchte ich LiaScript gerne bei uns als Option für Dokumentation und Trainings für agile Teams anbieten. Mal schauen, wie die Kollegen am Montag auf den MVP/Prototypen reagieren. 

Aber zum Verständnis: War der Merkel für Dich oder mich? ;) 

Ich hatte den Exporter vorsorglich schon mal aktualisiert (aktuell `version: 2.5.7--0.10.30`) und die Wrap-Option aktiviert, aber der Score ist weiterhin undefined. Daher nehme ich an, dass der Merker für dich war?

**Comment by andre-dietrich** [comment]
Merke? Ich wollte nur sagen, nochmal zu aktualisieren und alles sollte automagisch gelöst sein ... 

Hier mein Befehl:

`liaex -i ../LiaScript/static/README.md -p ../LiaScript/static -f scorm2004 --scorm-masteryScore 80 --scorm-iframe`

der mastery-Score muss gesetzt werden, sonst reagiert das LMS anders als gedacht ...

In der Dev-Console müssten jetzt auch mehr Ausgaben gezeigt werden. Vielleicht steht da was drin?

Ansonsten könntest du noch im Hauptkommentar in LiaScript den Debug-Modus setzen.

```markdown
<!--
@onload
window.LIA.debug = true
@end
-->

# ...
```

in diesem Modus sollte die gesamt Interaktion mit den LiaScript-Servicen angezeigt werden. Hier könnte alles interessant sein, was mit SCORM beginnt ... 

PS: Das Script für die Anzeige wird nur bei der Erstellung neu gezeichnet. Ich dachte, wenn es auf einer einzelnen Seite angezeigt wird und man immer nachsieht, dann funktioniert es. Wenn die Quizze auf der gleichen Seite sind, dann aktualisiert es nur, wenn man die Seite wechselt und wieder zurückkehrt ... Im letzten Fall müsste man ein Polling implementieren oder vielleicht einen Observer ...

Wenn ihr ab und zu auch ein paar offene Lehrinhalte mit LiaScript erstellt, dann ist es eine WinWin Situation ;-) die neuen Features haben sich schonmal gelohnt :-)

**Comment by andre-dietrich** [comment]
@rfuehrer ... Die Einstellungen sind jetzt auch in der Doku ... Der Vollständigkeit halber habe ich noch eine option `data-hint-button` eingefügt, die genauso funktioniert wie `data-solution-button` ...

https://liascript.github.io/course/?https://raw.githubusercontent.com/liaScript/docs/master/README.md#73

PS: im neuen SCORM-output werden jetzt auch die Nutzer-Einstellungen wie Farbe, Schriftgröße, etc. gespeichert ...

**Comment by rfuehrer** [comment]
Ich werde da sin meinem Prototypen für das Security-Training einbauen und testen. Klappt soweit alles. Mit dem Gauge am Ende habe ich allerdings das Problem, dass die Animation nicht abgespielt wird und der Zeiger immer gleich auf dem Ergebnis steht. Die Zahl in dem Gauge allerdings hochgezählt wird. Hast Du das schon mal festgestellt? (Link zum Format kann ich bei Interesse senden)

**Comment by andre-dietrich** [comment]
Ja, ich würde es gerne mal sehen ... Kannst es mir auch via LiaScript(Add)web.de schicken ...

**Comment by rfuehrer** [comment]
Ansonsten kannst Du gerne hier unter Scorm Cloud schauen :) 

https://app.cloud.scorm.com/sc/InvitationConfirmEmail?publicInvitationId=6b73b8aa-8567-4f45-8c60-0b73a5d4f701

Die Einladung ist für zwei Registrierungen bis zum 08.03.2023 offen. Sollte jemand anderes in den Thread mitlesen, gerne auch hier Feedback zu dem Inhalt :)

**Comment by andre-dietrich** [comment]
Hi, ich habe mal ein kleines Beispiel hochgeladen:

https://github.com/LiaPlayground/SCORM-Progress

https://liascript.github.io/course/?https://raw.githubusercontent.com/LiaPlayground/SCORM-Progress/main/README.md#1

Dabei wird über die globale Variable window.SCORE eine Möglichkeit gestülpt die Veränderungen zu beobachten. Die Gauge-Anzeige müsstest du noch mit deinem Styling anpassen. Es werden zwei Macros erstellt, `@score` und `@_score`, das erste ist nur ein kleiner Helfer und übergibt als ersten Parameter eine UID, die wird vom erzeugten Script genutzt um einen Observer mit einer ID einmalig anzumelden. Dann wird der erste Parameter `@0` dem zweiten Macro als zweiter Parameter übergeben ... im Code einfach nur nach `@0` und `@1` suchen, dass sind die Platzhalter, so kannst du noch mehr Konfigurationen selber definieren ...

So können auf verschiedenen Seiten die SCORES angezeigt werden und diese werden auch live aktualisiert ... Jedes script/macro hat eine eigene `send.lia` Funktion die alles direkt zurück sendet und somit auch asynchron genutzt werden kann ... 

Hoffe das funktioniert bei dir ... 

PS: den Exporter hatte ich nochmal geupdated, bei der `--scorm-iframe` Lösung wurde ein unnötiger margin eingefügt, dies wurde gefixt ...
