### ISSUE TITLE
[Feature] Show line numbers in code blocks

### ISSUE THREAD

**Issue by rfuehrer** [LiaScript/LiaScript#125]
In code blocks, displaying source code with line numbers is helpful for referencing in the text. Currently, the display of code does not support line numbers.

It would be helpful to have a built-in way that line numbers can be optionally displayed.

Unfortunately the tried prismjs does not work, because behind the language "line-numers" must be specified, which is interpreted in liascript as the name of the file.

Example: https://davidl.co.uk/post/adding-line-numbers-to-your-markdown-code-blocks

An integrated solution or an example of how an inclusion would ideally work would be helpful.

**Comment by andre-dietrich** [comment]
Hi, this is already included, you can apply the following syntax, to change the look of your code-snippets ...

https://liascript.github.io/course/?https://raw.githubusercontent.com/liaScript/docs/master/README.md#121

In general, within interactive code line numbers are not displayed, since it might show only pseudo-code or or just snippets ... Executable code will display line-numbers, which might be helpful for debugging ... However, you can enable or disable this behavior in both types ...

**Comment by rfuehrer** [comment]
Hi Andre,

so, wieder Wechsel nach deutsch (bei der Intro-Frage bin ich gerne in en glich, damit die Community den Impulse mit lesen kann ;) )

Danke für die Hinweise. Ich habe dank des Link etwas gespielt. Bei dem folgenden Snippet habe ich festgestellt, dass die Zeilennummern der `data-marker` von der angezeigten Zeile abweichen. Die Anzeige der Marker ist in Zeile 12 und 16, angegeben werden muss allerdings bei `data-marker` 11 und 15. Ist das ein Bug oder works-as-designed? Das tritt unabhängig von `data-firstLineNumber` auf.

```
Line 12 reads untrusted XML from the request and line 16 uses XStream to deserialize this payload without having set a strict whitelist of allowed types to deserialize. 

<!-- data-firstLineNumber="1" data-showGutter="true" data-marker="11 28 11 57 error text; 15 25 15 33 error text;" -->
```
```
Runner runner = null;
Connection connection = null;
try {
  connection = DAOUtils.getConnection();
  RunnerDAO runnerDAO = new RunnerDAO(connection);
  RunnerForm runnerForm = (RunnerForm)form;
  runner = new Runner( runnerForm.getId(), runnerForm.getUsername(), runnerForm.getFirstname(),
    runnerForm.getLastname(), runnerForm.getStreet(), runnerForm.getZip(),
    runnerForm.getCity(), runnerForm.getDateOfBirthAsDate(), runnerForm.getCreditcardNumber() );
  runnerDAO.updateRunner(runner);
  runner = runnerDAO.loadRunner(runner.getId());
  String marshalledBase64 = request.getParameter("state");
  if (marshalledBase64 != null && marshalledBase64.trim().length() > 0) {
    String xml = new String(Base64.getDecoder().decode(marshalledBase64.trim()));
    XStream xstream = new XStream();
    Map stateMap = (Map) xstream.fromXML(xml);
  }
} finally {
  if (connection != null) connection.close();
}
request.setAttribute("runner", runner);
request.setAttribute("UpdateResultMessage", "<b>Your data has been saved</b>");

```

**Comment by rfuehrer** [comment]
Zudem ist die letzte Zeile im Code durch die Scrollbars immer überdeckt, so dass man eine Leerzeile einfügen muss. Das könnte man über Stylesheets anpassen, aber ohne Customzing fehlt halt immer die unter Hälfte :)

**Comment by andre-dietrich** [comment]
Hi, welchen Browser nimmst du und welches Betriebssystem? Das muss wahrscheinlich nochmal nachgesteilt werden. Per default ist jeder Browser selber für die Darstellung seiner Scrollleisten zuständig ... Ich muss mal schauen, wie man das am elegantesten lösen kann. Unten dein Beispiel (links Firefox und rechts Chrome).

![image](https://user-images.githubusercontent.com/3089101/221127468-89f44fc6-e0ca-4a22-ac5c-57d6e56b87fe.png)

Die Darstellung von Firefox finde ich sogar eleganter ... Ich hatte das folgende snippet verwendet (hier ging es ohne Leerzeile):

```` markdown
<!--
    data-showGutter="true"
    data-marker="11 28 11 57 error text;
                 15 25 15 33 error text;"
-->
``` java
Runner runner = null;
Connection connection = null;
try {
  connection = DAOUtils.getConnection();
  RunnerDAO runnerDAO = new RunnerDAO(connection);
  RunnerForm runnerForm = (RunnerForm)form;
  runner = new Runner( runnerForm.getId(), runnerForm.getUsername(), runnerForm.getFirstname(),
    runnerForm.getLastname(), runnerForm.getStreet(), runnerForm.getZip(),
    runnerForm.getCity(), runnerForm.getDateOfBirthAsDate(), runnerForm.getCreditcardNumber() );
  runnerDAO.updateRunner(runner);
  runner = runnerDAO.loadRunner(runner.getId());
  String marshalledBase64 = request.getParameter("state");
  if (marshalledBase64 != null && marshalledBase64.trim().length() > 0) {
    String xml = new String(Base64.getDecoder().decode(marshalledBase64.trim()));
    XStream xstream = new XStream();
    Map stateMap = (Map) xstream.fromXML(xml);
  }
} finally {
  if (connection != null) connection.close();
}
request.setAttribute("runner", runner);
request.setAttribute("UpdateResultMessage", "<b>Your data has been saved</b>");
```
````

Aber danke für den Hinweis, ich werde mich Kundig machen ...

---

Bezüglich der Zeile ... Das scheint aus dem Ace-Editor zu kommen, er zeigt die Zeilennummern ab 1 an, zählt aber, wie es scheint, intern ab 0 (müsseen ein Informatiker und Designer zusammen gemacht haben ;-) ... Die Zeilennummern gebe ich direkt an Ace weiter, jetzt bin ich aber unentschlossen, ob wir das ändern und damit alle Projekte verrücken, die dieses Feature vielleicht nutzen oder ob man es in der Doku nochmal explizit erwähnt ... vielleicht könnte der firstLineNumber-Wert auch als Korrekturwert genutzt werden ... Jedenfalls danke für den Hinweis, muss gelöst werden ;-)
