### ISSUE TITLE
Templates do not work locally

### ISSUE THREAD

**Issue by Rochan-HM** [LiaScript/LiaScript#131]
Hello,

## Issue

I am trying to run the [PyScript template](https://raw.githubusercontent.com/liaTemplates/PyScript/main/README.md#1) using LiaScript locally. However, it does not work.

## Steps to reproduce

1. Clone the repo locally
2. Run `yarn watch` or equivalent command
3. Paste in the URL as `https://raw.githubusercontent.com/liaTemplates/PyScript/main/README.md#1`

## Expected Behavior

It should work locally as it does on the main [LiaScript website](https://liascript.github.io/course/?https://raw.githubusercontent.com/liaTemplates/PyScript/main/README.md#2)

## Actual Output

Nothing is displayed

![image](https://user-images.githubusercontent.com/43693294/232139413-bf5174b0-8ecd-4ba5-ab6b-239bc4753401.png)

## Alternative Approaches

I also tried manually setting up PyScript as per the instructions given on the [official PyScript website](https://pyscript.net/)

Firstly, add 

```md
link: https://pyscript.net/latest/pyscript.css
script: https://pyscript.net/latest/pyscript.js
```
to the initialization header.

Next, try running with
```html
<lia-keep>
    <py-script>print("Hello")</py-script>

    <py-repl>
    </py-repl>
</lia-keep>
```

It should print hello or at-least display a repl. However, it does not show up.

Any clues as to how to solve this?

**Comment by andre-dietrich** [comment]
Hi, try out locally the following:

```` md
<!--
persistent:  true
import: https://raw.githubusercontent.com/liaTemplates/PyScript/main/README.md
-->

# Example

``` python @PyScript.repl
print('Sammy says, \'Hello!\'')
```
````

This will generate the following 

![image](https://user-images.githubusercontent.com/3089101/232195180-bd63ba45-8ede-4a21-9abd-d2c1bf3a81a1.png)

---

You don't have to compile it manually, all required scripts and styles should be loaded ... We did only add custom macros, this way we can write Markdown code-snippets, which are interpreted as python ... It is recommended to set persistent to true, this way the pyscript generated changes on the DOM will not be destroyed, when you switch to another slide ...

**Comment by Rochan-HM** [comment]
Unfortunately, it still does not work. This is all that appears when I run it locally.
![image](https://user-images.githubusercontent.com/43693294/232343037-d486829e-c39d-44f4-a1de-cc38ea4c82fd.png)

Perhaps is it somehow related to this error?
![image](https://user-images.githubusercontent.com/43693294/232343255-ad89a0c0-a1ea-4cd1-9642-e49720149b5d.png)

**Comment by andre-dietrich** [comment]
Hi, do you compile LiaScript by yourself and run it in dev-mode? From your screenshot I can see that the pyscript modules seem to be loaded properly. The error does only affect the ace-editor, in dev-mode it cannot properly load themes, paths are only correctly set (I don't know why), if the project is compiled.

![image](https://user-images.githubusercontent.com/3089101/232398775-c61dfcf2-ab0f-4310-9f9b-cb3ab7fc32f0.png)

If you just use vscode and run the preview via this plugin:

https://marketplace.visualstudio.com/items?itemName=LiaScript.liascript-preview

is the problem still there?

Compiling LiaScript requires to run some patches, at the moment I don't know if this is related with your problem. But these patches were necessary to use URLs other than http and https or to prevent elm from crashing when an external screen-reader is used...

**Comment by andre-dietrich** [comment]
because this seems to work:

https://liascript.github.io/course/?https://pastebin.com/raw/AK1FMRvK#1

in my case ... does it work for you?

**Comment by Rochan-HM** [comment]
Thank you so much for responding!

Yes, I am compiling LiaScript in dev mode right now. I wanted to try playing around with LiaScript and see if I can add some new features or customize it.

Yes, it works locally using the VSCode plugin. It also works when I use `liascript.github.io`. It just does not work when I compile LiaScript locally.
Even when I build it for production using `yarn build`, it does not work.

I think that it might have to do something with the patches you mentioned 🤔

**Comment by Rochan-HM** [comment]
After hours of debugging, I see that this solution works nicely.

````md
<!--
author:   Your Name

email:    your@mail.org

version:  0.0.1

language: en

narrator: US English Female

comment:  Try to write a short comment about
          your course, multiline is also okay.

link:     https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css
          https://cdn.jsdelivr.net/gh/liatemplates/pyscript@0.0.4/dist/pyscript.css

script:   https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js
          https://cdn.jsdelivr.net/gh/liatemplates/pyscript@0.0.4/dist/pyscript.min.js

@Python3: @Python3.run(@uid,```@0```)

@Python3.run
<script>
const currEle = document.querySelector("#py_@0");
currEle.innerHTML = "<py-repl class='notranslate' output-mode='replace' output='py_out_@0'>@'1</py-repl>";
</script>

<div id="py_@0"></div>
<div id="py_out_@0" class="text-2xl font-mono my-2 mx-8"></div>
@end

-->

# Course Main Title

This is your **course** initialization stub.

```python @Python3
print("Hello World")

a = 1
b = 2
```
````

However, I get the codeblock as a string as well.
Might need to debug the macro a bit more 🤔 

![image](https://user-images.githubusercontent.com/43693294/233016715-c19e6c8f-da14-484a-ab11-fcb2a560c397.png)

**Comment by Rochan-HM** [comment]
Thank you so much for all your help.

In case anyone else finds this, I used this snippet to successfully get PyScript to run.

````md
<!--
link:     https://cdn.jsdelivr.net/gh/liatemplates/pyscript@0.0.4/dist/pyscript.css

script:   https://cdn.jsdelivr.net/gh/liatemplates/pyscript@0.0.4/dist/pyscript.min.js
          
@Python3: @Python3.run(@uid,```@0```)

@Python3.run
<script>
const currEle = document.querySelector("#py_@0");
currEle.innerHTML = "";
const newEle = document.createElement("div");
newEle.innerHTML = "<py-repl class='notranslate' output-mode='replace' output='py_out_@0'>@'1</py-repl>";
currEle.append(newEle);
</script>
<div id="py_@0"></div>
<div id="py_out_@0" class="text-2xl font-mono my-2 mx-8"></div>
@end

-->

# Example

```python @Python3
print("Hello World")

a = 1
b = 2
```
````

**Comment by andre-dietrich** [comment]
@Rochan-HM ... sorry for the late response, I have been working on gap-text for quizzes, to be released soon ;-)

However, did you perform the entire build process as described here:

https://github.com/LiaScript/LiaScript/#build

within the patches folder, there is a Makefile, that should perform all patches automatically for you ...
---
Additionally your-script tag in LiaScript does behave a bit differently. Every script can have a result, that is directly printed in place. Thus, when you do:

``` md
<script>2+5</script>
```

The result 7 should appear within the text. All results will be interpreted as strings, except of `undefined`, but you can also instruct LiaScript to interpret the content either as HTML or as LiaScript and to rerun parsing on the result of the script

``` md
<script>
"HTML: <span style='color: red'>Hello World</span>"
</script>
```

Thus, a script can also be styled in LiaScript ;-) ... Take a look at the following section to get an overview ...

https://liascript.github.io/course/?https://raw.githubusercontent.com/liaScript/docs/master/README.md#194

**Comment by Rochan-HM** [comment]
Oh! I see! That makes sense now.
It was my bad. I had to read the documentation more carefully 😅 

Thank you so much for all your work on LiaScript! It is really such a fantastic project!
