### ISSUE TITLE
[Feature request] Include diagram generation software

### ISSUE THREAD

**Issue by vgoehler** [liaScript/LiaScript#14]
CodiMd has some great diagram generators included for flow charts, sequence diagrams and so on.
The usage is very easy and on the data side, meaning that you only have to specify the relations of the blocks.
See the [CodiMd documentation Section](https://demo.codimd.org/features?both#Diagrams) with links to the involved javascript projects.

It would be good to have this features in LiaScript also. The ASCII System ist quite good but a bit cumbersome as you have to draw the diagram yourself.

**Comment by SebastianZug** [comment]
Hi Volker, now I understood that you meant plantUML in our discussion. André already prepared a plugin providing an environment to integrate sequential, class or activation diagrams in Lia documents. 

Take a view on it :-)

https://liascript.github.io/course/?https://raw.githubusercontent.com/liaTemplates/plantUML/master/README.md#3

**Comment by andre-dietrich** [comment]
Hi @vgoehler , happy valentines day ;), actually I integrated a port of svgbob to elm, which is responsible for the ASCII-art features. I hope in the future, it will be better integrated into LiaScript with inlining Markdown, colors, etc. But for now, it should be compatible to svgbob and therefore it is also possible to use this editor for drawings: 

https://ivanceras.github.io/svgbob-editor/

Similar features would be also great in the Atom-Editor... I will keep this in mind for later ...
