### ISSUE TITLE
Problem with escaping

### ISSUE THREAD

**Issue by alexeygrinevich** [LiaScript/LiaScript#140]
I writing an example for ' and " in javascript. It seems I'm unable to do code block with this line:

var escapingQuotes = 'Escaping a quote: \'Single quotes\' or "Double quotes"';

Here is an example:

https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA1NWCCjKT8pJzVUozyzJUEgtTk4syMxL5+Xi5UpISMhKLEssTi7KLCjh5SpLLIJLB5bml6QWK9gqqLtCRRQSFQpBglYKMerBQH5OKoRfHKOukF+koOSSX5oEF1NStwYbz8tlAzHdziEzr6AUaImNPlQA5AAAqSj3u5wAAAA=

And here is what I get:

![image](https://github.com/LiaScript/LiaScript/assets/25929131/d45a8148-82c9-484c-97a4-ad0ad77b909e)

It seems that it is extra-escaping internal ' char. Is there a way to force it to not escape it?

**Comment by alexeygrinevich** [comment]
Some update. Managed to bypass this problem by doing own unescaping like that:

https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA9VQwU7DMAy9V+o/PIVDUgm190E34AQSFwTHHRLaaM3o4tC4K59PuqIhLnDGlmzJz+/Zehd4GoktwkCvvT3kWZ69dC6CvMVEw1tczSOtNfbmaGIzuMB51pCP1Nuyp52CeKaDhXyfdVqw/WAJ56NrrUBx4ubZ9cJcL1SGjY3jWkUeinqdajnY0JvGqmqbQlZudylSF8VPQMyATF0WV2epo+mTQqr1Iqv0jfNhZJ2Oz6D63kgT8fhwu0JkCiK9VZ3/mvNuZEydYTChJUyOO/CXGxsox+hMhISA8S22uihxT9O8Pfp02gRbjf7kAxxv/jRO/+Kc/kfWfQJzKsoaRAIAAA==

But there is still a problem if JS contains all three quotation symbols: \` ' and "

Frankly, it is just a potential problem, not a showstopper, but I've no ideas of workaround. Would be awesome to know how to deal with it also:)

**Comment by andre-dietrich** [comment]
@alexeygrinevich Thanks for the effort, I will have to check it ... this seems to be a serious bug, this is unfortunately introduced due to the different string handling of Elm and JavaScript. We had to implement a slight workaround for escaped strings, which seem to fail in this case ...

**Comment by andre-dietrich** [comment]
@alexeygrinevich ... you can try out the escapes now ... it should be fixed:

https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA1NWCCjKT8pJzVUozyzJUEgtTk4syMxL5+Xi5UpISMhKLEssTi7KLCjh5SpLLIJLB5bml6QWK9gqqLtCRRQSFQpBglYKMerBQH5OKoRfHKOukF+koOSSX5oEF1NStwZZgGoa2EJeLhuIfXYOmXkFpUBrbfShAiAdAJQFNA6uAAAA

**Comment by alexeygrinevich** [comment]
Thanks a lot, you are extremely helpful!
