### ISSUE TITLE
Macro definition with XML comment

### ISSUE THREAD

**Issue by alexeygrinevich** [LiaScript/LiaScript#143]
Hi Andre,

This snippet demonstrates another minor problem that I managed to reproduce:

https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA62QMW/CMBSEd0v+DwddayQidWmhAlVVp85d80heG6PYieyXUP59HQMSA2xd7+7d93SrmTFaabVxVIXuy0rz1jnHXpaTqtUq+ahJyMSmO3wMIhzWcwkDz2HMq1ZlWe5ppFgF24tWIwUQ1nh6yVauZl/fRBT/DMhxrR7wOYFwSCRUJ9Skv/+S61vGEuacaCimrnPkEbtBYCWrBdj1ckRrPccFtr4GjxyO0lj/AxvxnYzn+8NdWEViTXeI1tk2vZ7TJ1T+bz9EQef5ine7No31B0rdDjmsAQAA

The problem is. Whenever we have a macro defined in the comment and it has own comment:

...
@end
-->
...
@someMacro

The macro shows up corrupted unless there are 2 empty lines between @someMacro and 

Luckily it has a straight forward workaround. Although would be great to have it either fixed or mentioned in the docs.

Br/Alexey

**Comment by andre-dietrich** [comment]
Thanks a lot for the report, if you look at the example, the problem should be gone and everything should work as expected. I was missing an additional rule that eats newly add newline as a block ...

**Comment by alexeygrinevich** [comment]
Great, it works now!
