### ISSUE TITLE
Problem calling macro with param containing @

### ISSUE THREAD

**Issue by alexeygrinevich** [LiaScript/LiaScript#144]
Hi Andre,

This sample demonstrates my problem. I need to pass a value containing @. It always gets truncated at the position at @. I tried various types of escaping with no luck:

https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA12OQQrCMBBF94Xe4YsbXURci0gvIHThATJthjaSmpKJ2t7eThcKrh7z/gzzzxtjyqKqcJ3RRQrwghwxkggsVc2hjYMFCQgDtUmTRANnTmWx3K2uVqVjWVhr7/QiaZMf85IfV7Wu8sMpjbkotqj1BTmXeKH47qH61jMyTxlNnNBwiG9IH5/BwXkZA82/Uqe/Artvsv8Ad5GTydUAAAA=

Maybe it is worth to have some sort of post-processing of HTML-symbols (i.e. &amp; &quot; etc - so we have guaranteed workaround for passing any symbol as a parameter?)

I hope that makes sense,
Br/Alexey

**Comment by andre-dietrich** [comment]
@alexeygrinevich ... also this should now work as expected ... Thank you again, this is very helpful...

**Comment by alexeygrinevich** [comment]
That is more than awesome! Thanks a lot!
