### ISSUE TITLE
Ability to link to a specific slide within a LiaScript course

### ISSUE THREAD

**Issue by rosemm** [LiaScript/LiaScript#153]
Hello!
We often find ourselves waiting to point a learner to a specific slide within a course, to answer a particular question (e.g. https://liascript.github.io/course/?https://raw.githubusercontent.com/liaScript/docs/master/README.md#5). 
However, (I think?) because LiaScript is saving the user's state, including which "page" of the course they're on, we've found that links to specific slides don't work if the learner has already opened the course previously -- it just redirects to wherever they were last time they looked at the course. I imagine this was intentional behavior, so learners could work part way through a course and then come back to finish it another time and drop right back in where they left off, but I wonder if the ability to link to specific slides is actually more valuable. 
So my question is this: Is there a way to link to specific slides such that it would override LiaScript's memory of the last slide a learner was on?
Thank you so much for your excellent work on LiaScript! We love it.

**Comment by andre-dietrich** [comment]
Thanks a lot for reporting ... this seems to be a bug ... I will fix this ...

**Comment by andre-dietrich** [comment]
Hi @rosemm ... could you try it again? In my case it seems to work now, but I did not change anything :see_no_evil: ... Maybe this was a short GitHub error ...

**Comment by rosemm** [comment]
Hi, yes, it's mysteriously working for me now, too! So never mind! :) 
We'll keep an eye on this behavior and let you know if it starts happening again. Thanks, as always, for your amazing support!
