### ISSUE TITLE
Rendering of buttons in Firefox broken

### ISSUE THREAD

**Issue by cagix** [LiaScript/LiaScript#155]
When opening the docs examples in Firefox on iOS/iPadOS, all buttons are not being rendered correctly: 
<img width="834" alt="Screenshot 2024-01-13 at 16 04 09 jpeg" src="https://github.com/LiaScript/LiaScript/assets/20356276/345befa3-e0f4-47ec-88b9-8002b42505d0">

In mobile Safari the buttons show up as expected.

**Comment by andre-dietrich** [comment]
Thanks for reporting ... Sorry, I could not reproduce this error so far, but it looks like a CSS problem, where the webfonts could not be loaded. I guess you already tried a hard reload?

If the problem persists, could you please share a screenshot of the developers console? I don't own an IPad, so maybe following some of the mentioned steps here:

https://discourse.mozilla.org/t/how-do-i-debug-firefox-on-ios/111414/4

could shed a light on the problem :see_no_evil: 

Thanks a lot ...

**Comment by cagix** [comment]
Ah, the culprit was the (default?) setting: "block web fonts" has been active. Once this is deactivated, everything works as expected. Sorry for bothering you. Thx for this interesting project!
