### ISSUE TITLE
Issues with settings panel

### ISSUE THREAD

**Issue by pwab** [liaScript/LiaScript#17]
I've found a few issues in the settings panel.

### Scrollbars everywhere
As can be seen in the screenshot every button and the whole panel itself have an unnecessary vertical scrollbar. This does not happen on mobile devices:

| Desktop 	| Mobile 	|
|---------	|--------	|
|  <img width="200" src="https://user-images.githubusercontent.com/19271185/81856843-a6bd1f80-9561-11ea-8d51-3dfbeb9b4169.png">	|  <img width="200" src="https://user-images.githubusercontent.com/19271185/81898449-f7139c00-95b8-11ea-97bf-c4cd5dc042db.jpg">	|

The share panel has the same problem:
![grafik](https://user-images.githubusercontent.com/19271185/81858464-13d1b480-9564-11ea-923d-9c53211a25fd.png)

### Buttons are confusing
If you want to choose another font for code view you can select from a list. The buttons are used in the same way (choose a theme) but why buttons instead of a list? This is a confusing UX at first.

### Nightmode
I couldn't find the night-mode setting because I misinterpreted the word "Color" next to it. Also the moon is hard to see. Maybe use 🌙 or 🌜 instead of 🌝 ?
Would it be possible to automatically switch to a dark code style when changing to night-mode?

### Font scaling
A font scale < 100% does also scale the frame sizes. At 80% I get a messy UI on my not FHD screen:
![grafik](https://user-images.githubusercontent.com/19271185/81857718-ef290d00-9562-11ea-8c4e-37a51ff9022e.png)

And also the gray-theme button seems to have a problem in dark-mode because the font color changes to a light one while the background is also in a light gray. This is due to the fact that the background color does not correspond to the theme color (see theme button in the last screenshot).

**Comment by andre-dietrich** [comment]
Thanks for the great issue-collection, on this list, at least I hope so, everything could be fixed ... it is now updated in the atom previewer plugin, as well as on the website ...
