### ISSUE TITLE
button to copy code-block to clipboard

### ISSUE THREAD

**Issue by jamesellinger** [LiaScript/LiaScript#178]
Thanks for providing this great tool. So far I really like the functionality of LiaScript.

I am currently considering using LiaScript to deliver part of a data science course in the autumn. The students need to use Python via Google's Colab or their own device. 

I understand how to dsiplay Python code via LiaScript, but I was wondering if there is anyway to create a button that will copy the entire code-block to the clipboard?

**Comment by andre-dietrich** [comment]
Dear James, this is a very good idea, I will try to add this by the end of the week since I also thought of this a couple of times :see_no_evil:

**Comment by andre-dietrich** [comment]
I made an update on the main site ... for the plugins and editors I will update this later ;-) 

![image](https://github.com/LiaScript/LiaScript/assets/3089101/20a9f0f8-0623-4b45-9265-cf6aa2dd91ed)

**Comment by jamesellinger** [comment]
Wondeful, thank you!
