### ISSUE TITLE
Links in settings panel aren't readable when using dark-mode

### ISSUE THREAD

**Issue by pwab** [liaScript/LiaScript#18]
**Test link:** https://liascript.github.io/course/?https://raw.githubusercontent.com/liaScript/docs/master/README.md#1

**SeeTranslations:**
![grafik](https://user-images.githubusercontent.com/19271185/81858633-52676f00-9564-11ea-98fa-8fb6b306839c.png)

**And Informations:**
![grafik](https://user-images.githubusercontent.com/19271185/81858584-4380bc80-9564-11ea-92f7-fe965aea997e.png)

By the way it should be Information instead of Information**s**

**Comment by andre-dietrich** [comment]
I was not aware of this ... thx
