### ISSUE TITLE
Issues with toolbar

### ISSUE THREAD

**Issue by pwab** [liaScript/LiaScript#19]
I've found some issues with the toolbar.

### Search is buggy
Test link: https://liascript.github.io/course/?https://raw.githubusercontent.com/liaScript/docs/master/README.md#1

Just type in `Tools` (it's the second header after the start page). It can't be found. It seems that the search only goes through the paragraphs and not the headings?

### Delete search terms with an X
If I'm searching for stuff the navigation reduces itself to the pages that may contain my search terms. This is okay but it leads to the problem that when I want to get back to the normal navigation overview I have to delete my search term. A simple `X` at the end of the search bar could be added to instantly delete the current search terms and to get back to the normal view.

### Buttons
The buttons for burger menu, index, previous and next page and also mode are very small. They are barely 'readable'. Also this is a problem on mobile devices but I'll discuss this in another issue.

Despite the small size their width seems to be variable. They don't have a static ratio like quadratic or 16:9 or whatever. Instead their width differs a lot an so the click area does. See here for reference:

![mSCNZdDt5b](https://user-images.githubusercontent.com/19271185/81859996-614f2100-9566-11ea-957d-b5e4e2637c81.gif)

### Index
I was confused about the home button. I thought it would bring me to the first page but I got to my own Index page (UX problem). I tried to get back but the back button is not working there (UX). Maybe another symbol could be used for the Index page? Or it could be moved down - left side of the user settings button. This would make it more clear that this button has nothing to do with the current course.

**Comment by andre-dietrich** [comment]
Yes, this was definitely a bug, and the X button was a good point ... at the next version, I hope, I will integrate a better inbrowser search such as lunr.js...
