### ISSUE TITLE
Issues on mobile

### ISSUE THREAD

**Issue by pwab** [LiaScript/LiaScript#20]
I've tried to use the LiaScript docs page as a test for mobile usage. Here is a list of issues I've found there.

### Starts with an open navigation bar
When opening the page the nav sidebar is opened. You have to click on the burger menu to start reading. It would be better if the nav-bar is hidden on mobile by default and only shows up by clicking on the burger menu (or adding the function that you could open it with a swipe from the left border).
<img width="200" src="https://user-images.githubusercontent.com/19271185/81896407-d77a7480-95b4-11ea-925a-397bc3f1aa3c.jpg">

### Out of range problems
Some elements seem to get out of the view. This is sometimes hard to prevent (e.g. for tables) but also there are some issues with text overflow and such. I tracked it in the docs with some screenshots:

<img width="200" src="https://user-images.githubusercontent.com/19271185/81896844-b5352680-95b5-11ea-8f87-347c3d9df157.jpg"> <img width="200" src="https://user-images.githubusercontent.com/19271185/81896853-b9614400-95b5-11ea-87e3-374db72812b7.jpg"> <img width="200" src="https://user-images.githubusercontent.com/19271185/81896857-bbc39e00-95b5-11ea-9bed-24963d38cb4d.jpg">
<img width="200" src="https://user-images.githubusercontent.com/19271185/81896878-c3834280-95b5-11ea-9696-37552e2cf15d.jpg"> <img width="200" src="https://user-images.githubusercontent.com/19271185/81896884-c54d0600-95b5-11ea-8cbf-0b274ca75610.jpg"> <img width="200" src="https://user-images.githubusercontent.com/19271185/81896891-c7af6000-95b5-11ea-889d-5ab4029e6b4f.jpg">

### Zooming with two fingers
I accidently zoomed into it with the zoom gesture. I think this is a useful feature on mobile but I wasn't able to reset to 100%. Since the I'm getting problems like cut end of pages (not able to scroll down any further) and so buttons get lost:

<img width="200" src="https://user-images.githubusercontent.com/19271185/81897561-2de8b280-95b7-11ea-89f5-3fdba104fd5c.jpg">

I don't know if this problem comes from firefox (that I'm using on the phone) so that the adress bar on the bottom simply isn't substracted from the screen height or it is something that could be done on the websites settings. I also had other troubles with the adress bar unpredictably hiding my settings panel:

![ezgif-7-d37cedf1c503](https://user-images.githubusercontent.com/19271185/81898012-15c56300-95b8-11ea-837b-5293ff4df993.gif)

### Cut radio buttons
I stumbled upon the issue that the radio buttons seem to be cut on the top and bottom of a quiz. This happens only on mobile devices:

![photo_2020-05-14_07-27-20](https://user-images.githubusercontent.com/19271185/81898197-80769e80-95b8-11ea-9655-76531fe1d95d.jpg)

**Comment by andre-dietrich** [comment]
Some CSS overflow bugs could be fixed, the screenshot with the large table show a bug, since the quotation was not large enough and the same was true for the quizzes ... but the overlong tables result from an additional styling parameter (width=500px) that was set just as an example. The open navbar on mobile was also fixed, now there is a check, if the screenwidth is larger than 620 pixels... but zooming, cut off radio-buttons, and mobile firefox, will be fixed in the future ...

Thanks a lot ...

**Comment by andre-dietrich** [comment]
Closing this, since the new design solves these issues also on mobile and feature phones ...
