### ISSUE TITLE
KaTeX can not be styled in liascript

### ISSUE THREAD

**Issue by tilman-schieber** [LiaScript/LiaScript#205]
# Expected Behaviour

According to the [documentation](https://katex.org/docs/font#font-size-and-lengths), it is possible to style KaTeX using CSS rules.
I expect it to be possible to style the math fonts by adding a rule for class `.katex`

# Observed Behaviour
For some reason any rules referring to the class `.katex` do not appear in LiaScript's output.

See this [Example](https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA1WMTQoCMQyF94XeIWJ30kHHhTL+MIeYCxQn0tBOKzbgiHh3U9xoePBe8vFyXFirlVZ94WfEmprgGGd4aQUylxzzvbtRCget3pX7zT+DX9hjGqtbe66m1RIGLFzT4KmASJ4zPIg9lDwhUIqUECYnh0gBwbQGXBrBXE/tvNrvvhtLuxO2XZvmA7LWjS+0AAAA)

Using the font-size example from the KaTeX documentation does not work either.

**Comment by andre-dietrich** [comment]
Within the next release, this should be solved. Although the shadow-dom is defined as open, it does not access the global styles ... however this is now done manually and injected ....

**Comment by andre-dietrich** [comment]
Works now ...

![image](https://github.com/user-attachments/assets/8c1ae24d-fbdf-4ccf-823b-5122589a122f)
