### ISSUE TITLE
Comma in String Parameter breaks Script

### ISSUE THREAD

**Issue by eguvep** [LiaScript/LiaScript#214]
Minimal example. This code is working:
```
# Tst
<!--

@tst
<script>
    let text=@0
	// ...
</script>
@end

-->

@tst("Hello World!", "Hello Lia!" )
```
The following macro call is NOT working, (note comma in "Hello, World!"):

`@tst("Hello, World!", "Hello Lia!" )`

**Comment by andre-dietrich** [comment]
Hi, you can use backticks to surround your elements, and blocks can also be used, if you want to ... 

``` markdown
<!--
@tst
<script>
    let text="@0"
    text + "---" + text
</script>
@end
-->

# Tst

@tst(`Hello, World`, "Hello Lia!" )
```

[LiveEdit](https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA7NR1NXl4nIoKS7hsilOLsosKLHjUgCCnNQShZLUihJbJQcDJbAIiKegraCkq6urBKRBXC4bfZgeh9S8FC4uXV07Li5lhRCgaWAzNRI8UnNy8nUUwvOLclISdBSUwHwFn8xERSUFTQDBpLdYfQAAAA==)

Here is a better explanation on how this might be used [documentation](https://liascript.github.io/course/?https://raw.githubusercontent.com/LiaScript/docs/master/README.md#passing-parameters)

If you want to pass more complex parameters, such as json, yaml, etc. you can also use this code-blocks as parameters, described on the following section or links (in this case the URL is the last parameter and URL translation will be applied automatically)...

**Comment by eguvep** [comment]
Oh, thanks a lot! I read that part, but must have overlooked that section mentioning the comma issue. Sorry for bothering you!

**Comment by andre-dietrich** [comment]
no problem ;-)
