### ISSUE TITLE
ASCII Art broken?

### ISSUE THREAD

**Issue by eguvep** [LiaScript/LiaScript#216]
On two different machines, and three different browsers, I can not open pages with ASCII art anymore. 
Example:
https://liascript.github.io/course/?https://raw.githubusercontent.com/liaScript/docs/master/README.md#141
Any ideas?

**Comment by eguvep** [comment]
Thanks for the quick response and for downgrading elm svg-bob until the issue is solved. In this way I can use my scripts meanwhile.

**Comment by eguvep** [comment]
... ups, this just seemed to work – until reload

**Comment by andre-dietrich** [comment]
now it works again ... I had to remove the elm-optimize step from the build ... this was weird, because the latest updates did not had anything to do with the ascii images. Downgrading did not solve the problem ...

**Comment by eguvep** [comment]
Sounds strange. However, it works again! Thanks a lot for taking care about this. The issue can be closed, right?
