### ISSUE TITLE
[Feature request] Private GitHub LiaScript courses

### ISSUE THREAD

**Issue by SebastianZug** [LiaScript/LiaScript#3]
Hi Andre,

currently, it is not possible to "execute" course from private GitHub repositories. Inexperienced users asked for this feature hoping to implement first steps with LiaScript without public visibility. Of course, they did not consider that the history of the attempts is still available :-) 

Looking forward to further discussions!

Sebastian

**Comment by andre-dietrich** [comment]
I do not know if I support closed courses ;) but therefor, the url has to be handled differently internally ...

**Comment by jhc-at-home** [comment]
Is it reasonable to suggest these users experiment in the Atom editor (with plugin) or even a local instance and a clone of their private repository.

**Comment by SebastianZug** [comment]
One of my colleagues located at another part of the university would like to receive some hints for his first LiaScript course. I know, availability is our topic, but for this scenario the consideration of private repositories would be helpful.

**Comment by andre-dietrich** [comment]
See https://github.com/liaScript/LiaScript/wiki/Hosting-List

Maybe using Dropbox as an simple way of quickly sharing courses privately is also an option, without having a github account/project ...

**Comment by andre-dietrich** [comment]
Unfortunately, after testing, it seems, that sharing courses from a private GitHub-repo seems to be impossible. Every resource gets its own "token", which seems also to change. Thus, only adding the private token to the image URLs does not work ...

I will close this issue ...
