### ISSUE TITLE
Upgrade to eCharts v5

### ISSUE THREAD

**Issue by andre-dietrich** [LiaScript/LiaScript#42]
A new version of eCharts is online, upgrade might be usefull:

https://echarts.apache.org/en/index.html

**Comment by pwab** [comment]
Is it possible to use the eCharts library directly in Markdown? Or this is only for backend rendering purposes?

**Example**
Like writing the script on the left with options and data and then get a visualized graph like on the right:
https://echarts.apache.org/examples/en/editor.html?c=area-stack-gradient

**Comment by andre-dietrich** [comment]
Hi, this is actually possible. LiaScript therefore uses an internal webcomponent called lia-chart, it is defined here:

https://github.com/LiaScript/LiaScript/blob/development/src/typescript/webcomponents/chart.ts

so you can pass your option via the `<lia-chart option="...." ...` attribute, however, this might be tedious and cumbersome, if you need to to some calculation, thus the following does also work. This is a script that does your calculation for you. `runOnce` simply means, that there is no need for a recalculation, I mean update whenever the user visits this slide, thus the script runs only once and preserves the result.

The last line is important! If your last statement would only be a string or an int, LiaScript would print this out as the result of your string, however, it is also possible to tell LiaScript, that it should take care of the result, and interpret it as an HTML element, so there is some kind of post-processing done internally. Next to `send.html` you could also use `send.liascript` and pass in a string of some LiaScript Markup, if it is a table or a quiz, it will be handled accordingly. There is some more stuff about scripts at the end of the documentation...

> All scripts are inspect-able by user, thus if you double-click on the result, an editor should pop-up with the code, and if you edit it and click somewhere, so that the editor looses the focus, the code gets reevaluted. However, reloading the page will restore the old settings.

> Last but not least, the update you are refering to is currently only in the development branch. The next release will be a bit bigger... However, the code below should also work, but at the moment it is not eCharts 5 but eCharts 4.9... 

``` html
<script runOnce style="display: inline-block; width: 100%">
var option = {
    title: {
        text: '堆叠区域图'
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'cross',
            label: {
                backgroundColor: '#6a7985'
            }
        }
    },
    legend: {
        data: ['邮件营销', '联盟广告', '视频广告', '直接访问', '搜索引擎']
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: [
        {
            type: 'category',
            boundaryGap: false,
            data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
        }
    ],
    yAxis: [
        {
            type: 'value'
        }
    ],
    series: [
        {
            name: '邮件营销',
            type: 'line',
            stack: '总量',
            areaStyle: {},
            emphasis: {
                focus: 'series'
            },
            data: [120, 132, 101, 134, 90, 230, 210]
        },
        {
            name: '联盟广告',
            type: 'line',
            stack: '总量',
            areaStyle: {},
            emphasis: {
                focus: 'series'
            },
            data: [220, 182, 191, 234, 290, 330, 310]
        },
        {
            name: '视频广告',
            type: 'line',
            stack: '总量',
            areaStyle: {},
            emphasis: {
                focus: 'series'
            },
            data: [150, 232, 201, 154, 190, 330, 410]
        },
        {
            name: '直接访问',
            type: 'line',
            stack: '总量',
            areaStyle: {},
            emphasis: {
                focus: 'series'
            },
            data: [320, 332, 301, 334, 390, 330, 320]
        },
        {
            name: '搜索引擎',
            type: 'line',
            stack: '总量',
            label: {
                show: true,
                position: 'top'
            },
            areaStyle: {},
            emphasis: {
                focus: 'series'
            },
            data: [820, 932, 901, 934, 1290, 1330, 1320]
        }
    ]
};

send.html(`<lia-chart option='${JSON.stringify(option)}'></lia-chart>`)

</script>
```

**Comment by pwab** [comment]
Tested and it works perfectly. Thanks!

**Comment by andre-dietrich** [comment]
Just for fun, if you want to interact with the diagram you can also use multiple scripts. The parameter `output="topic"` is used for publishing and `input="range"` can be associated with any kind of HTML-input. Whenever the result of this script changes, it is published under topic `startPoint`. The second, bigger script is subscribed for such changes via `start = @input(`startPoint`) * 100`, which simply means, replace this addInput-topic with the published value ... the script is then recalculated again ... and via double-click on the script-body, the user can inspect and modify the code...

> It does not have to be a chart, it can be anything ...

![demo](https://user-images.githubusercontent.com/3089101/106819724-7b8fd880-667a-11eb-9206-90a1f071f857.gif)

``` html
This is some basic increment that
<script input="range" value="12" default="12" output="startPoint">@input</script>
you can manipulate. It's value is published on topic `startPoint`. Within the script below,
this value is imported and added to the first data-series.

<script runOnce style="display: inline-block; width: 100%">

var start = @input(`startPoint`) * 100

var option = {
    title: {
        text: '堆叠区域图'
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'cross',
            label: {
                backgroundColor: '#6a7985'
            }
        }
    },
    legend: {
        data: ['邮件营销', '联盟广告', '视频广告', '直接访问', '搜索引擎']
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: [
        {
            type: 'category',
            boundaryGap: false,
            data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
        }
    ],
    yAxis: [
        {
            type: 'value'
        }
    ],
    series: [
        {
            name: '邮件营销',
            type: 'line',
            stack: '总量',
            areaStyle: {},
            emphasis: {
                focus: 'series'
            },
            // NOTE ...................................................................
            data: [start+120, start+132, start+101, start+134, start+90, start+230, start+210]
        },
        {
            name: '联盟广告',
            type: 'line',
            stack: '总量',
            areaStyle: {},
            emphasis: {
                focus: 'series'
            },
            data: [220, 182, 191, 234, 290, 330, 310]
        },
        {
            name: '视频广告',
            type: 'line',
            stack: '总量',
            areaStyle: {},
            emphasis: {
                focus: 'series'
            },
            data: [150, 232, 201, 154, 190, 330, 410]
        },
        {
            name: '直接访问',
            type: 'line',
            stack: '总量',
            areaStyle: {},
            emphasis: {
                focus: 'series'
            },
            data: [320, 332, 301, 334, 390, 330, 320]
        },
        {
            name: '搜索引擎',
            type: 'line',
            stack: '总量',
            label: {
                show: true,
                position: 'top'
            },
            areaStyle: {},
            emphasis: {
                focus: 'series'
            },
            data: [820, 932, 901, 934, 1290, 1330, 1320]
        }
    ]
};

send.html(`<lia-chart option='${JSON.stringify(option)}'></lia-chart>`)

</script>
```

**Comment by pwab** [comment]
Maybe both of these two posts should find their way into the docs. At least that screenrecording!
