### ISSUE TITLE
Formatierungsfehler durch Verwenden von ""

### ISSUE THREAD

**Issue by Florian2501** [LiaScript/LiaScript#45]
Mir ist aufgefallen, dass durch das Verwenden von Anführungszeichen ("") in einem Textabschnitt, die Formatierung von folgenden Objekten nicht mehr funktioniert. Definitiv konnte ich es bei den Kästchen beobachten, die man mit ` ` erzeugt und bei einem Link.

Das Kästchen wurde einfach nicht angezeigt, sondern nur Test mit den schrägen Strichen ohne Formatierung. 
Bei dem Link konnte man keinen eigenen Name vergeben bzw. wurde einfach alles wieder genau so angezeigt wie man es in Markdown eingegeben hatte also z.B. statt `title` als Link konnte man `[title](http://goo.gl/fGXNvu)` sehen und es wurde nicht als Link erkannt.

Die Probleme verschwanden als ich die `"` durch zwei `'` ersetzte. Dabei war es egal, ob die Anführungszeichen noch offen oder bereits geschlossen waren. Danach funktionierte die Formatierung nicht mehr, davor aber schon, als würden die Anführungszeichen die Formatierung deaktivieren.

Vielen Dank!

**Comment by andre-dietrich** [comment]
Danke Florian, für den Hinweis ... Der Teil des Parsers, der für die Elemente mit Hochkommas zuständig ist, war etwas zu gierig, die zusätzliche Ausnahme müsste das Problem behoben haben. Jedenfalls konnte ich es danach nicht mehr reproduzieren ...

LG
