### ISSUE TITLE
image does not load if an underscore is used in alt-text

### ISSUE THREAD

**Issue by EliasTechnik** [LiaScript/LiaScript#48]
I recreated and demonstrated the bug [https://LiaScript.github.io/course/?https://github.com/EliasTechnik/EnglishPresentation/blob/main/imagebug.md](https://LiaScript.github.io/course/?https://github.com/EliasTechnik/EnglishPresentation/blob/main/imagebug.md)

If an underscore is used in the alt-text of an image its get interpreted as a text-formatting character. 

That does not load: `![ttally_controler class](img/lo_res/imagebug/ttally_controller.jpg)`

That does load: `![ttally controler class](img/lo_res/imagebug/ttally_controller.jpg)`

It seems that the underscore in the alt-text is a problem. Maybe the underscore in the path contributes also to it.

I am not sure if an underscore in an alt-text should be interpreted as a text-formatting character. If so please close this issue because it's not a bug.

**Comment by andre-dietrich** [comment]
Thanks for the report...
