### ISSUE TITLE
Course with no heading (or not at the top) does not render at all

### ISSUE THREAD

**Issue by jhc-at-home** [liaScript/LiaScript#8]
In the following examples LiaScript renders a blank slide:

* Example containing no headers: https://liascript.github.io/course/?https://raw.githubusercontent.com/jhc-at-home/scratch/master/NoHeaders.md
```markdown
Some text

Some more text
```

* Example with heading after some text: https://liascript.github.io/course/?https://raw.githubusercontent.com/jhc-at-home/scratch/master/WithHeaders.md
```markdown
Some text

# A heading

Some more __text__
```

**Comment by andre-dietrich** [comment]
Yes, it expects the first heading to be the title of the document, I will add an extra rule for that, so that the first section can also have no title  ... Thanks ;)

**Comment by andre-dietrich** [comment]
I fixed this, the default behavior is now, that this initial content without a heading gets ignored. Probably this can be used as an extra space for adding comments to a course, which shall/is not visible in LiaScript ...
