### ISSUE TITLE
Markdown within HTML tags is rendered as plain text

### ISSUE THREAD

**Issue by jhc-at-home** [liaScript/LiaScript#9]
Example: https://liascript.github.io/course/?https://raw.githubusercontent.com/jhc-at-home/scratch/master/Simple.md#1

This contains:
```markdown
<div>
*Some* _markdown_
</div>
```

Expected result (see note):
*Some* _markdown_

Actual result:
<pre>*Some* _markdown_</pre>

Note: Apparently [github isn't working properly](https://github.github.com/gfm/#example-122) either on this.

**Comment by andre-dietrich** [comment]
There is currently a problem with the HTML parsing. I give all the power to the HTML parser (https://github.com/hecrj/html-parser) that parses only HTML and also the inner parts as HTML or plain text... One of my next updates, will be an internal HTML parser that allows to parse inner Markdown.

There is currently also another issue with HTML... I recommend to use only a unique main tag, I mean

``` HTML
<div> <span> ... </span> <span> ... </span> </div> --- this is okay

<div> <div> <div> ..... </div> </div>
# some hashtags
</div> --- this might cause in some rare cases sometimes problems ... 
```

The preprocessor uses for speed-reasons only some simple rules for to run over html, the inner hash tag might be recognized as a heading...

**Comment by jhc-at-home** [comment]
I've a branch of this `html-parser` that I'm working on at the moment that allows the caller to render `Text` Elements. Would this make sense or shall I abandon this approach? Once it's ready I'll still file a PR with @hecrj to get his opinion.

**Comment by andre-dietrich** [comment]
Oh damn it, I just did the same, I am sorry, I should have checked the pull requests. At the moment it is quite new for me, that someone is making pull requests to LiaScript. My appologies ...

To be honest, I did the same and integrated the elm-html parser into LiaScript @hecrj ... but adapted it slightly to work with LiaScript. I did only test it with plain html and markdown, but now mixing is possible, like it is shown in the snippet below. Also the Atom Plugin should now work with this new version. 

``` html
<details>

<summary>$ f(a,b,c) = (a^2+b^2+c^2)^3 $</summary>

<p>
Here is the source data that is discussed in the article ...
</p>

<dl>
  <dt style="color: red">Definition list</dt>
  <dd>Is something people use sometimes.</dd>

  <dt><b>Markdown in HTML</b></dt>
  <dd>Does _work_ **very** well. Use HTML <em>tags</em>.</dd>
</dl>

</details>
```

But from time to time time there might be some issues by using the Atom-Plugin. All content is put into spans, that, if double-clicking them, trigger a jumping of the cursor at the text. These spans might cause a different HTML than it is used at the website/pwa...

By the way, hiding content in LiaScript or on Github is now also possible, I wrote some notes about it at: https://github.com/liascript/docs#html-hiding-content

I am sorry for overseeing your PR :.(.

**Comment by andre-dietrich** [comment]
@jhc-at-home, ... just saw, that the pull request was not about the mixing html markdown parsing ;)

**Comment by jhc-at-home** [comment]
Hi Andre,

> just saw, that the pull request was not about the mixing html markdown parsing ;)

I tried very hard to modify `html-parser` to integrate it into recursively parsing LiaScript. Indeed what you saw in that branch is an early attempt. Instead now I've bitten the bullet and started trying to parse HTML using your parser combinators library to get tight integration and non-inline markdown.
The branch is at [jhc-at-home/LiaScript/markdown-in-html](https://github.com/jhc-at-home/LiaScript/tree/markdown-in-html)

By the way,

> I am sorry for overseeing your PR :.(.

No problem :)

**Comment by jhc-at-home** [comment]
> I've a branch of this `html-parser` that I'm working on at the moment that allows the caller to render `Text` Elements. Would this make sense or shall I abandon this approach? Once it's ready I'll still file a PR with @hecrj to get his opinion.

Here is Hectors response from slack:
> Would it be possible to transform the Node tree instead? In other words, whenever `html-parser` is called, process the resulting Node tree and call the markdown parser recursively on Text nodes.

> You could make the parser return Node, or simply write your own toVirtualDom for your AST indeed.

**Comment by jhc-at-home** [comment]
Ah indeed, you've already done this. I'll have to try it out later.

**Comment by jhc-at-home** [comment]
@andre-dietrich This works very well for our purposes. I think this bug can be closed
