### ISSUE TITLE
`>` in section title breaks whole course

### ISSUE THREAD

**Issue by Geist5000** [LiaScript/LiaScript#95]
If a section title contains the `>` character it breaks the whole course:

```
## Topic > Subtopic
```

The above example breaks the whole course

**Comment by andre-dietrich** [comment]
Thanks for reporting, that is a bug and should not happen ... I will fix this ...

**Comment by andre-dietrich** [comment]
Hi, this bug was caused during preprocessing and should now be fixed. Additionally \< and \> can now also be escaped, which should result in a slightly better parsing performance...

**Comment by Geist5000** [comment]
Works for me. Thanks for the fast fix
