### ISSUE TITLE
Uncomfortable notation of nested lists

### ISSUE THREAD

**Issue by Geist5000** [LiaScript/LiaScript#96]
If I want to create an unordered list with a nested list inside like so:

- Main List
  - Sublist start
  - Sublist Entry

I need to add an empty line before the sublist:
Works:
```
- Main List

  - Sublist start
```

Doesn't work

```
- Main List
  - Sublist
```

I would prefer the notation without the empty line.

**Comment by andre-dietrich** [comment]
This might be looking strange, but it is atm deeply embedded into the parsing process, which requires Markdown blocks to be separated by an empty line.

If you look at the following example, it is ambiguous, is it only one paragraph or one bullet-point with another nested bullet point.

``` markdown
- Some paragraph
  - that gets extended.
- Some more text
```

of course, this seems to be clearer, when multiple points are used:

``` markdown
- Some paragraph
  - bulletpoint 1
  - bulletpoint 2
  - ...
- Some more text
```
But for this case I would also prefer the separation by newlines:

``` markdown
- Some paragraph

  - bulletpoint 1
  - bulletpoint 2
  - ...

- Some more text
```
This provides a logical and visual separation of blocks, that can be identified immediately.

**Comment by Geist5000** [comment]
My wish originated from trying to migrate a normal markdown styled document into a LiaScript course. 

I understand that this change would be too time-consuming. 

I would suggest improving the documentation to point out that the empty line is actually needed to make a sublist work. Technically, it is explained in the "Content blocks" chapter, but for me, it wasn't clear a sublist is its own content block.

**Comment by andre-dietrich** [comment]
@Geist5000 ... You are right, I just added an additional note:

https://github.com/liaScript/docs#unordered-lists

Thanks again ;-)

**Comment by Geist5000** [comment]
Thanks for changing this so fast
