### ISSUE TITLE
Logo on course page

### ISSUE THREAD

**Issue by BeastyBlacksmith** [LiaScript/LiaScript#98]
I would like the logo specified in the header to also show up on the course page either above the search bar or isntead of the LiaScript logo above the content.

**Comment by andre-dietrich** [comment]
Hi, there is a logo definition and an icon ... logo is for historical reasons the larger image, also depicted on preview-cards. If you want to replace the little hummingbird, simply use `icon: url-to-image.png` ...

**Comment by BeastyBlacksmith** [comment]
That does work for me, thank you!
